---
# Meta Information
title: Pagoda Goods
description: 'Pagoda Goods is a group of friends living in DC, trying to start a cafe and collection of original goods & apparel.'
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true

markdown: kramdown

# Site Assets
logo: /uploads/pg-logo.svg
logo-icon: /uploads/pg-icon.svg

# Contact Information
email: info@pagodagoods.com
copyright: Pagoda Goods | 2016- All Rights Reserved

gems:
- jekyll-feed
exclude:
- Gemfile
- Gemfile.lock
